/*const arbol=new AvlTree();
arbol.insertar(25);
arbol.insertar(15);
arbol.insertar(30);
arbol.insertar(8);
arbol.insertar(10);
arbol.insertar(5);
arbol.insertar(28);
arbol.insertar(27);
arbol.insertar(40);
arbol.print();
arbol.delete(10);
//arbol.delete(10)
arbol.print();
//arbol.delete(30);
//arbol.insertar(50);
//arbol.insertar(100);
//arbol.print();
arbol.graficar()*/
